version: '3.8'
name: training

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: training-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ..:/var/www/
  nginx:
    image: nginx:1.26-alpine
    container_name: training-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../public:/var/www/public
      - ../src:/var/www/src
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  db:
    container_name: training-db
    image: mysql:8.4
    volumes:
      - ../storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: training_db
    ports:
      - 3306:3306
  phpmyadmin:
    container_name: training-phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=training-db